## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      
file.upload-dir: /home/yrseo/downloads
alpr.bin-dir: /usr/local/src/openalpr/openalpr/src/alpr